version: "3"
services:
  redis:
    image: "redis:latest"
    tty: true
    stdin_open: true
  server:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.dev
      context: ../
    tty: true
    stdin_open: true
    volumes:
      - ../:/fast-app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
