version: "3"
services:
  redis:
    image: "redis:latest"
    tty: true
    stdin_open: true
  server-test:
    build:
      dockerfile: ./Dockerfiles/Dockerfile.test
      context: ../
    tty: true
    stdin_open: true
    volumes:
      - ../:/fast-app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
