# docker file for development
FROM python:3.8-slim-bullseye

RUN mkdir /flask-app
WORKDIR /flask-app
COPY requirements.txt /flask-app
RUN pip install -r requirements.txt
COPY . /flask-app

ENV FLASK_APP=run.py
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["flask", "--debug", "run", "--host", "0.0.0.0"]
