name: Fastapi App Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    
    steps:
      - uses: actions/checkout@v3

      - name: Echo hello world
        run: echo Hello-world