name: Fastapi App Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    
    steps:
      - uses: actions/checkout@v3

      - name: Build the stack and run tests with Docker
        run: docker-compose -f ./Dockerfiles/Docker-compose-test.yaml up --build --exit-code-from server-test